// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGiQp8CjVXh1-NpHzw9VZZJi7HfWPEUig',
    appId: '1:578730057803:web:e35fabde0f62e3da64edce',
    messagingSenderId: '578730057803',
    projectId: 'nafaj-445a4',
    authDomain: 'nafaj-445a4.firebaseapp.com',
    storageBucket: 'nafaj-445a4.firebasestorage.app',
    measurementId: 'G-YZ7V03E949',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCID149fWB36yIB7a92EmXYQ_bna434JTU',
    appId: '1:578730057803:android:30d07e6ee1656d4b64edce',
    messagingSenderId: '578730057803',
    projectId: 'nafaj-445a4',
    storageBucket: 'nafaj-445a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEihC98AlHIxKFAVdyGs5jOfF4yF9jMAE',
    appId: '1:578730057803:ios:283733a03054591564edce',
    messagingSenderId: '578730057803',
    projectId: 'nafaj-445a4',
    storageBucket: 'nafaj-445a4.firebasestorage.app',
    iosBundleId: 'com.example.nafaj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEihC98AlHIxKFAVdyGs5jOfF4yF9jMAE',
    appId: '1:578730057803:ios:283733a03054591564edce',
    messagingSenderId: '578730057803',
    projectId: 'nafaj-445a4',
    storageBucket: 'nafaj-445a4.firebasestorage.app',
    iosBundleId: 'com.example.nafaj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGiQp8CjVXh1-NpHzw9VZZJi7HfWPEUig',
    appId: '1:578730057803:web:0b446a65f738955964edce',
    messagingSenderId: '578730057803',
    projectId: 'nafaj-445a4',
    authDomain: 'nafaj-445a4.firebaseapp.com',
    storageBucket: 'nafaj-445a4.firebasestorage.app',
    measurementId: 'G-GKEPT7XFFF',
  );
}
