CREATE TABLE IF NOT EXISTS jobs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category_id INT,
  user_id INT NOT NULL,
  budget DECIMAL(10,2) NOT NULL,
  location VARCHAR(500),
  latitude DECIMAL(10,8),
  longitude DECIMAL(11,8),
  deadline DATETIME,
  status ENUM('open', 'in_progress', 'completed', 'cancelled') DEFAULT 'open',
  views INT DEFAULT 0,
  applications INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
  INDEX idx_status (status),
  INDEX idx_user_id (user_id),
  INDEX idx_category_id (category_id),
  INDEX idx_created_at (created_at)
);
