CREATE TABLE IF NOT EXISTS vendors (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(20) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  business_name VARCHAR(255) NOT NULL,
  owner_first_name VARCHAR(100),
  owner_last_name VARCHAR(100),
  business_type VARCHAR(100),
  shop_address TEXT,
  city VARCHAR(100),
  status ENUM('active', 'inactive', 'suspended', 'pending_approval') DEFAULT 'pending_approval',
  profile_image VARCHAR(500),
  banner_image VARCHAR(500),
  bio TEXT,
  rating DECIMAL(3,2) DEFAULT 0,
  reviews_count INT DEFAULT 0,
  total_products INT DEFAULT 0,
  total_orders INT DEFAULT 0,
  total_earnings DECIMAL(10,2) DEFAULT 0,
  ntn_number VARCHAR(100),
  documents_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  INDEX idx_email (email),
  INDEX idx_phone (phone),
  INDEX idx_status (status),
  INDEX idx_business_name (business_name)
);
