CREATE TABLE IF NOT EXISTS drivers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(20) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  license_number VARCHAR(100) UNIQUE,
  vehicle_type VARCHAR(100),
  vehicle_plate VARCHAR(50),
  status ENUM('active', 'inactive', 'suspended', 'pending_verification') DEFAULT 'pending_verification',
  profile_image VARCHAR(500),
  bio TEXT,
  rating DECIMAL(3,2) DEFAULT 0,
  reviews_count INT DEFAULT 0,
  total_rides INT DEFAULT 0,
  total_earnings DECIMAL(10,2) DEFAULT 0,
  documents_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  INDEX idx_email (email),
  INDEX idx_phone (phone),
  INDEX idx_status (status),
  INDEX idx_license (license_number)
);
