CREATE TABLE IF NOT EXISTS products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  vendor_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(100),
  price DECIMAL(10,2) NOT NULL,
  discount_price DECIMAL(10,2),
  stock_quantity INT DEFAULT 0,
  unit VARCHAR(50) DEFAULT 'piece',
  images JSON,
  status ENUM('active', 'inactive', 'out_of_stock') DEFAULT 'active',
  rating DECIMAL(3,2) DEFAULT 0,
  reviews_count INT DEFAULT 0,
  total_sales INT DEFAULT 0,
  is_featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE,
  INDEX idx_vendor_id (vendor_id),
  INDEX idx_category (category),
  INDEX idx_status (status),
  INDEX idx_name (name)
);
